// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ptgwkcciqonagjojgqrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0Z3drY2NpcW9uYWdqb2pncXJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MTY3NTUsImV4cCI6MjA3MTE5Mjc1NX0.OmVnniX0MYbeVSbZTXg-qeCxXyAglEpNOhp2CFh1hY8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});